apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    alertmanagerMain:
      volumeClaimTemplate:
        metadata:
          name: alertmanager-pvc
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd
          resources:
            requests:
              storage: 50Gi
          accessModes:
            - ReadWriteOnce
    prometheusK8s:
      retention: 14d
      retentionSize: 220GB
      volumeClaimTemplate:
        metadata:
          name: prometheus-pvc
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd
          resources:
            requests:
              storage: 300Gi
          accessModes:
            - ReadWriteOnce