apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - lokistack-verify.yaml
  - logging-verify.yaml
  - coo-uiplugin-verify.yaml
  - monitoring-pvcclaim-verify.yaml
  - updateservice-verify.yaml
  - quayregistry-verify.yaml