apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: alertmanager-pvc-alertmanager-main-0
    namespace: openshift-monitoring
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: alertmanager-pvc-alertmanager-main-1
    namespace: openshift-monitoring
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: prometheus-pvc-prometheus-k8s-0
    namespace: openshift-monitoring
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 300Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: prometheus-pvc-prometheus-k8s-1
    namespace: openshift-monitoring
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 300Gi
    phase: Bound
