apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - htpasswd-idp.yaml

secretGenerator:
- name: custom-htpasswd
  namespace: openshift-config
  files:
  - htpasswd
  options:
    disableNameSuffixHash: true
