apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
spec:
  installPlanApproval: Automatic
  name: cluster-logging
  channel: stable-6.4
  source: redhat-operator-index      # as per catalogsource Name
  sourceNamespace: openshift-marketplace
