apiVersion: updateservice.operator.openshift.io/v1
kind: UpdateService
metadata:
  name: update-service-oc-mirror
  namespace: openshift-update-service
spec:
  graphDataImage: registry.apps.oct4-hub.telco.te/redhat/openshift/graph-image:latest
  releases: registry.apps.oct4-hub.telco.te/redhat/openshift/release-images
  replicas: 2
