apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-odf
  namespace: openshift-logging
type: Opaque
data:
  # Populated at policy render time from the OBC-generated Secret/ConfigMap
  access_key_id:
  access_key_secret:
  bucketnames:
  endpoint:

