apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-odf
  namespace: openshift-logging
type: Opaque
data:
  access_key_id: '{{ fromSecret "openshift-logging" "loki-bucket-odf" "AWS_ACCESS_KEY_ID" }}'
  access_key_secret: '{{ fromSecret "openshift-logging" "loki-bucket-odf" "AWS_SECRET_ACCESS_KEY" }}'
  bucketnames: '{{ fromConfigMap "openshift-logging" "loki-bucket-odf" "BUCKET_NAME" | base64enc }}'
  endpoint: '{{ printf "https://%s:%s" (fromConfigMap "openshift-logging" "loki-bucket-odf" "BUCKET_HOST") (fromConfigMap "openshift-logging" "loki-bucket-odf" "BUCKET_PORT") | base64enc }}'
